comment:
  # header: "Please note the following requirement:"
  footer: "\
    ---\n\n
    > &nbsp; &#9; &nbsp; &#9;  &nbsp; &#9;  &nbsp; &#9; Be sure to [join the community](http://slack.layer5.io), if you haven't yet and please leave a :star: [star on the project](../stargazers) :smile:
    "

labels:
  - name: framework/discourse
    labeled:
      issue:
        body: This issue has been labeled with 'framework/discourse'. Note that prior to commencing you need to create an account [here](https://staging-discuss.layer5.io/) and then ask for the admin access. After that start contributing to the discuss forum.
        action: open
