title: Layer 5
name: Lee Calcote
email: lee@layer5.io
name:  Layer5.io
description: A community-curated collection of service meshes.
baseurl: ""
url: "https://layer5.io"

parallax_image_one: assets/images/cube.png #-header-large.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

portfolio_heading: Workshops
portfolio_type: cards

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

skills: 
    - name: docker
#   - name: android
#   - name: angularjs
#   - name: apache
#   - name: appcelerator
#   - name: apple
#   - name: atom
#   - name: babel
#   - name: backbonejs
#   - name: bitbucket
#   - name: bootstrap
#   - name: bower
#   - name: c
#   - name: chrome
#   - name: codeigniter
#   - name: coffescript
#   - name: confluence
#   - name: cplusplus
#   - name: csharp
#   - name: css3
#   - name: cucumber
#   - name: d3js
#   - name: debian
#   - name: devicon
#   - name: django
#   - name: docker
#   - name: doctrine
#   - name: dot-net
#   - name: drupal
#   - name: erlang
#   - name: facebook
#   - name: firefox
#   - name: foundation
#   - name: gatling
#   - name: gimp
#   - name: git
#   - name: github
#   - name: gitlab
#   - name: go
#   - name: google
#   - name: gradle
#   - name: grunt
#   - name: gulp
#   - name: heroku
#   - name: html5
#   - name: ie10
#   - name: illustrator
#   - name: inkscape
#   - name: itellij
#   - name: java
#   - name: jasmine
#   - name: javascript
#   - name: laravel
#   - name: less
#   - name: linux
#   - name: meteor
#   - name: mocha
#   - name: mongodb
#   - name: moodle
#   - name: mysql
#   - name: nginx
#   - name: nodejs
#   - name: nodewebkit
#   - name: oracle
#   - name: photoshop
#   - name: php
#   - name: phpstorm
#   - name: protractor
#   - name: postgresql
#   - name: python
#   - name: pycharm
#   - name: rails
#   - name: react
#   - name: redhat
#   - name: redis
#   - name: ruby
#   - name: rubymine
#   - name: safari
#   - name: sass
#   - name: sequelize
    - name: slack
#   - name: sourcetree
#   - name: ssh
#   - name: swift
#   - name: symfony
#   - name: tomcat
#   - name: travis
#   - name: trello
#   - name: twitter
#   - name: typescript
#   - name: ubuntu
#   - name: vim
#   - name: visualstudio
#   - name: vuejs
#   - name: webpack
#   - name: webstorm
#   - name: windows8
#   - name: wordpress
#   - name: yii
#   - name: zend

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Github

session: Session

#Contact / Social
github: https://github.com/layer5io
medium: https://layer5.io
slack: https://layer5io.slack.com/
twitter: https://twitter.com/layer5
blog: https://layer5.io
docker: https://hub.docker.com/u/layer5/


baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it empty
#url: http://localhost:4000/ #the url of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: UA-2969471-4 # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: none # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thank you. Enjoy!

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
  - jekyll-sitemap

# Reference
# http://www.fabiolamanna.it
# https://github.com/jameshamann/jekyll-material-theme
# https://github.com/VincentGarreau/particles.js
# https://cssgradient.io
# https://coolbackgrounds.io