name: layer5-ng
on:
  push:
    branches:
      - layer5-ng
    tags:
      - "v*"
  pull_request_target:
    branches:
      - layer5-ng

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      # - name: Build project
      #   run: npm run build

      - name: Preview deploy to Netlify
        id: deploy-netlify
        uses: netlify/actions/cli@master
        if: github.event_name == 'pull_request_target'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=public

      - name: Netlify Preview URL
        uses: unsplash/comment-on-pr@master
        if: github.event_name == 'pull_request_target'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT: "This pull request is being automatically deployed to Netlify.\n\n🔍 Inspect: ${{ steps.deploy-netlify.outputs.NETLIFY_LOGS_URL }}\n✅ Preview: ${{ steps.deploy-netlify.outputs.NETLIFY_URL }}"
        with:
          msg: ${{ env.OUTPUT }}
          check_for_duplicate_msg: false

      # - name: Production deploy to Netlify
      #   uses: netlify/actions/cli@master
      #   if: (github.event_name == 'push') && endsWith(github.ref, '/layer5-ng')
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #   with:
      #     args: deploy --dir=public --prod
  
      - name: Build and Deploy on GH Pages
        run: npm run deploy
