name: Preview Site Wrapper
on:
  pull_request:
    branches: [ layer5-ng ]
    types: [opened, synchronize, edited, reopened]

jobs:
  triger-previewing-site:
    runs-on: ubuntu-18.04
    steps:
      - name: Triger Inner workflow
        run: echo "triger inner workflow"
